apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: spark:3.1.2
          command: ["/bin/bash", "-c", "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"]
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_MEMORY
              value: "1G"
            - name: SPARK_MASTER
              value: "spark://spark-master:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: spark
    role: worker
