apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark-zeppelin
  labels:
    app: spark
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:latest
        ports:
        - containerPort: 7077
        - containerPort: 8080
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPARK_MASTER_PORT
          value: "7077"

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: spark-zeppelin
  labels:
    app: spark
    role: master
spec:
  type: NodePort
  ports:
  - name: spark
    port: 7077
    targetPort: 7077
  - name: webui
    port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: spark
    role: master
