apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: spark-zeppelin
  labels:
    app: spark
    role: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        - name: SPARK_WORKER_PORT
          value: "7078"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: spark-zeppelin
  labels:
    app: spark
    role: worker
spec:
  type: NodePort
  ports:
  - name: webui
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: spark
    role: worker

